### ISSUE TITLE
Retain custom _MIN_TARGET_TEMPERATURE_STEP during update

### ISSUE THREAD

**Issue by NicholasChaplin** [TheNoctambulist/hass-airtouch#1]
### Checklist

- [X] This issue is not a duplicate feature request of [previous feature requests](https://github.com/thenoctambulist/hass-airtouch/issues?q=is%3Aissue+label%3A%22feature-request%22+).
- [X] This only contains 1 feature request (if you have multiple feature requests, open one feature request for each feature request).

### Proposal

Enable a custom value for _MIN_TARGET_TEMPERATURE_STEP to be retained during an update. 

Currently, _MIN_TARGET_TEMPERATURE_STEP = 1 is reset to  _MIN_TARGET_TEMPERATURE_STEP = 0.5 after each update.

**Comment by TheNoctambulist** [comment]
I've added a configuration option in v0.6.0 so that you can set a different minimum temperature step without modifying the code.
Use the "CONFIGURE" button on the AirTouch integration page to change the value and it should persist across updates.
