### ISSUE TITLE
Reboot causes “address in use” error

### ISSUE THREAD

**Issue by J-Lich** [TheNoctambulist/hass-airtouch#11]
### System Health details

logger:%20homeassistant.config_entries%0ASource%3A%20config_entries.py%3A604%0AFirst%20occurred%3A%20October%2016,%202024%20at%209%3A35%3A00%20AM%20(5%20occurrences)%0ALast%20logged%3A%2010%3A21%3A25%20AM%0A%0AError%20setting%20up%20entry%20AirTouch%205%20for%20airtouch%0ATraceback%20(most%20recent%20call%20last)%3A%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/config_entries.py%22,%20line%20604,%20in%20async_setup%0A%20%20%20%20result%20=%20await%20component.async_setup_entry(hass,%20self)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/config/custom_components/airtouch/__init__.py%22,%20line%2054,%20in%20async_setup_entry%0A%20%20%20%20discovery_results%20=%20await%20pyairtouch.discover(%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/local/lib/python3.12/site-packages/pyairtouch/factory.py%22,%20line%20131,%20in%20discover%0A%20%20%20%20responses%20=%20await%20_search(remote_host)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/local/lib/python3.12/site-packages/pyairtouch/factory.py%22,%20line%20184,%20in%20_search%0A%20%20%20%20responses.extend(await%20search)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/local/lib/python3.12/asyncio/tasks.py%22,%20line%20631,%20in%20_wait_for_one%0A%20%20%20%20return%20f.result()%20%20%23%20May%20raise%20f.exception().%0A%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/local/lib/python3.12/site-packages/pyairtouch/comms/discovery.py%22,%20line%2055,%20in%20search%0A%20%20%20%20transport%20=%20await%20self._open_socket(responses)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/local/lib/python3.12/site-packages/pyairtouch/comms/discovery.py%22,%20line%2091,%20in%20_open_socket%0A%20%20%20%20sock.bind(local_address)%0AOSError:%20%5BErrno%2098%5D%20Address%20in%20use%0A

### Checklist

- [X] I have enabled debug logging for the integration.
- [X] This issue is not a duplicate issue of any [previous issues](https://github.com/thenoctambulist/hass-airtouch/issues?q=is%3Aissue+label%3A%22bug%22+)..

### Describe the issue

After every reboot the integration does not connect and requires the integration to be removed and re-set up to work again. 

We have two consoles for the same AC system, they both have static IPs, I have tried to auto discovery, and manual IP in put to no avail.

Wifi on both consoles appears to have no issues (I have set up a ping sensor to both, which I will continue to monitor - as I understand there is another console specific issue in rotation causing drop outs.

### Reproduction steps

1. Set-up Integration
2. Reboot

### Debug logs

```Text
logger:%20homeassistant.config_entries%0ASource%3A%20config_entries.py%3A604%0AFirst%20occurred%3A%20October%2016,%202024%20at%209%3A35%3A00%20AM%20(5%20occurrences)%0ALast%20logged%3A%2010%3A21%3A25%20AM%0A%0AError%20setting%20up%20entry%20AirTouch%205%20for%20airtouch%0ATraceback%20(most%20recent%20call%20last)%3A%0A%20%20File%20%22/usr/src/homeassistant/homeassistant/config_entries.py%22,%20line%20604,%20in%20async_setup%0A%20%20%20%20result%20=%20await%20component.async_setup_entry(hass,%20self)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/config/custom_components/airtouch/__init__.py%22,%20line%2054,%20in%20async_setup_entry%0A%20%20%20%20discovery_results%20=%20await%20pyairtouch.discover(%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/local/lib/python3.12/site-packages/pyairtouch/factory.py%22,%20line%20131,%20in%20discover%0A%20%20%20%20responses%20=%20await%20_search(remote_host)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/local/lib/python3.12/site-packages/pyairtouch/factory.py%22,%20line%20184,%20in%20_search%0A%20%20%20%20responses.extend(await%20search)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/local/lib/python3.12/asyncio/tasks.py%22,%20line%20631,%20in%20_wait_for_one%0A%20%20%20%20return%20f.result()%20%20%23%20May%20raise%20f.exception().%0A%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/local/lib/python3.12/site-packages/pyairtouch/comms/discovery.py%22,%20line%2055,%20in%20search%0A%20%20%20%20transport%20=%20await%20self._open_socket(responses)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%5E%0A%20%20File%20%22/usr/local/lib/python3.12/site-packages/pyairtouch/comms/discovery.py%22,%20line%2091,%20in%20_open_socket%0A%20%20%20%20sock.bind(local_address)%0AOSError:%20%5BErrno%2098%5D%20Address%20in%20use%0A
```

**Comment by TheNoctambulist** [comment]
Hi @J-Lich ,

Which type of home assistant installation do you use?
The error indicates that something on the same computer is already binding to the AirTouch discovery port. It's possible that restarting Home Assistant is not closing down properly or perhaps something else is using the same port.

Could you please provide full debug logs including shutdown and start-up of Home Assistant so that I can see the sequence of events before the error (you can turn debug logging on from the integration settings page).

It would also be helpful to have the System Health information from the Home Assistant installation as requested in the GitHub bug template (see https://www.home-assistant.io/more-info/system-health#github-issues).

**Comment by TheNoctambulist** [comment]
I'm closing this as not reproducible.
Feel free to open a new issue with the full debugging information requested as per the bug template.
